### ISSUE TITLE
Bible Translation not displaying for custom bible

### ISSUE THREAD

**Issue by rajesh-rav** [martijnlentink/propresenter-custom-bibles#7]
Hi brother,
First of all, thank you so much for this awesome tool. It solved the problem we were facing for ages. I was able to add the TAMIL Bible successfully using your script. One small issue is that in the options when I select show translation, it is just showing the TAMIL Bible and it’s not showing the English translation along side. Could you please look into this? 
Thanks and Regards,
Rajesh

**Comment by martijnlentink** [comment]
Hi Rajesh,

Thank you for raising this issue. I previously mentioned this behavior in the readme, but it appears that I have deleted that. I don't have had the time yet to tackle this though. When I have time I'll see if I can fix this. What you could do to have this fixed right now is that you would download the English bible as well using the script, then it will show up.

**Comment by Anudeep0978** [comment]
> Hi brother, First of all, thank you so much for this awesome tool. It solved the problem we were facing for ages. I was able to add the TAMIL Bible successfully using your script. One small issue is that in the options when I select show translation, it is just showing the TAMIL Bible and it’s not showing the English translation along side. Could you please look into this? Thanks and Regards, Rajesh

Hi Rajesh, 
I want to extract the telugu bible, I tried to change the bible_id in "retrieve_chapter_youversion.py" and execute it, but it is still extracting the same language that in git ( I think Dutch language). what are the headers you included, Can you please help me in extracting the telugu language bible.. 
Thanks in advance

**Comment by Anudeep0978** [comment]
Hi Martijn, 
I want to extract the telugu bible, I tried to change the bible_id in "retrieve_chapter_youversion.py" and execute it, but it is still extracting the same language that in git ( I think Dutch language). what are the headers you included, Can you please help me in extracting the telugu language bible..
Thanks in advance

**Comment by martijnlentink** [comment]
Hi Anudeep,

Thank you for your message. Is there a reason you are trying to run the Python script instead of using the executable directly? I would suggest trying that; download the standalone installer from the Releases section and run that instead. That should work, the ad hoc scripts do work but do contain hardcoded values in there and I used them mainly for testing purposes. I would advice against using them if you don't have thorough knowledge on Python.

If, after trying that, you have some more questions please open up a new issue instead of commenting on this one since your question is in no way related to the question Rajesh has.

**Comment by martijnlentink** [comment]
Added the possibility to overwrite free bible. When that option is used other bibles should still show up.
